[package]
name = "concurso-360"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1.49.0", features = ["full"] }
